### ISSUE TITLE
compatibility with kaldi models

### ISSUE THREAD

**Issue by mooseyboots** [boi4/subextractor#1]
thx for this script. i wonder does it work with kaldi models? i've installed vosk and a few different models from the vosk website's list of models. when i try to run this on a kaldi generic french model, it errors continually that it can't find all the files it needs. it looks for the mfcc.conf file in the root of the model dir, instead of in the conf subdir, and if i copy that file to where it is looking for it, it cannot find many other files.

**Comment by martianhi** [comment]
the model i tried it on is kaldi-generic-fr-tdnn_f-r20191016, and the dir has a different directory structure to e.g. vosk-model-small-fr-pguyot-0.3.

is this something i can easily modify in the script?

**Comment by martianhi** [comment]
ah, its all good. a vosk person let me know that the kaldi models aren't set up properly for their tests. i'm now using one of their other models.

**Comment by boi4** [comment]
Ok, cool, good luck :)
