### ISSUE TITLE
bumping to vosk 0.3.30?

### ISSUE THREAD

**Issue by mooseyboots** [boi4/subextractor#2]
hi again,

i'm trying hack up a very necro flask app for upload files, download srt subs using your extractor.

i noticed when i install vosk 0.3.30 into a new virtual environment for my project and run your extractor it gen_subparts fails and creates a single subtitle timestamp with no text. if i roll back to 0.3.29 the generation works again.

are you able to bump the required version, and can you explain how i might also, so as to keep up with vosk updates?

thanks again.

**Comment by boi4** [comment]
Hey, I will take a look at it this evening.
The script is based on [one of the vosk-api examples](https://github.com/alphacep/vosk-api/blob/master/python/example/test_ffmpeg.py). Maybe you can take a look there for now

**Comment by boi4** [comment]
Okay, last commit was September 2020, so I guess this won't help

**Comment by boi4** [comment]
I just saw this added to one of the python examples: https://github.com/alphacep/vosk-api/commit/2349e66a973a8c5eb4391a4f2bc5b8a375815e9f
can you add this line and test whether the tool works with v0.3.30 again?

**Comment by boi4** [comment]
They seem to have an srt example https://github.com/alphacep/vosk-api/blob/master/python/example/test_srt.py
maybe this repo here is useless? :laughing:

**Comment by martianhi** [comment]
hi thx for your response, adding the line fixed things for me.

yeah i saw they had an example but i got kinda hacking and learning with your script. i suspect it's not useless for learning stuffs...

thx again.
